class style:
    def __init__(self) -> None:
        self.headerHeight = 50
        self.adFrameHeight = 220
        self.adFrameWidth = 210
        self.bidFrameHeight = 140
        self.bidFrameWidth = 210
        self.serviceFrameHeight = 140
        self.serviceFrameWidth = 210
        self.offerFrameHeight = self.bidFrameHeight
        self.offerFrameWidth = self.bidFrameWidth
        self.adsContainerHeight = 200
        self.adsContainerWidth = 770
        self.bidsContainerHeight = 110
        self.bidsContainerWidth = 770
        self.approvedBidsContainerHeight = 110
        self.approvedBidsContainerWidth = 770
        self.yourAdsContainerHeight = self.adsContainerHeight
        self.yourAdsContainerWidth = self.adsContainerWidth
        self.bidsOnYourAdsContainerHeight = self.bidsContainerHeight
        self.bidsOnYourAdsContainerWidth = self.bidsContainerWidth
        self.servicesContainerHeight = self.approvedBidsContainerHeight
        self.servicesContainerWidth = self.approvedBidsContainerWidth
        self.adsConsoleHeight = 270
        self.adsConsoleWidth = 0  # fix this
        self.bidsConsoleHeight = 195
        self.bidsConsoleWidth = 0  # fix this
        self.approvedBidsConsoleHeight = 195
        self.approvedBidsConsoleWidth = 0  # fix this
        self.yourAdsConsoleHeight = self.adsConsoleHeight
        self.yourAdsConsoleWidth = self.adsConsoleWidth
        self.bidsOnYourAdsConsoleHeight = self.bidsConsoleHeight
        self.bidsOnYourAdsConsoleWidth = self.bidsConsoleWidth
        self.servicesConsoleHeight = self.approvedBidsConsoleHeight
        self.servicesConsoleWidth = self.approvedBidsConsoleWidth
        self.headerColor = "#7C9070"
        self.headerFont = ("American Typewriter", 24)
        self.arrowColor = "#7C9070"
        self.arrowFont = ("American Typewriter", 60)
        self.homePageFont = ("American Typewriter", 100)
        self.homePageColor = "#7C9070"
        self.tabsFrameColor = "#F97B22"
        self.tabBoxColor = self.tabsFrameColor
        self.containerBgColor = "#9CA777"
        self.consoleBgColor = self.containerBgColor
        self.tabNameFont = ("Arial", 16)
        self.adTitleFont = ("American Typewriter", 16)
        self.attributeFont = ("American Typewriter", 16)
        self.tabsFrameBorderColor = "green"
        self.refreshNeededColor = "orange"
        self.homePageColor = self.containerBgColor
        self.buyPageColor = self.containerBgColor
        self.sellPageColor = self.containerBgColor
        self.myServicesPageColor = self.containerBgColor
        self.settingsPageColor = self.containerBgColor
        self.adFramebg = self.containerBgColor
        self.adFrameTitleColor = self.containerBgColor
        self.adFramePowerColor = self.containerBgColor
        self.adFrameCoresColor = self.containerBgColor
        self.adFrameMemoryColor = self.containerBgColor
        self.adFrameStorageColor = self.containerBgColor
        self.adFramePriceColor = self.containerBgColor
        self.adFrameSellerColor = self.containerBgColor
        self.adFrameBuyButtonColor = "#FEE8B0"
        self.buyButtonFont = ("American Typewriter", 20)
        self.adFrameBuyButtonTextColor = "white"
        self.adFrameBuyButtonBorderColor = "black"
        self.adFrameBuyButtonActiveColor = "green"
        self.adFrameBuyButtonActiveTextColor = "white"
        self.sshAccessLinkFont = ("American Typewriter", 16)
        self.sshPasswordFont = ("American Typewriter", 16)
        self.sshHeaderFont = ("American Typewriter", 16)
        self.sshPasswordHeaderFont = ("American Typewriter", 16)
        self.approvedBidTitleColor = self.containerBgColor
        self.approvedBidStatusColor = self.containerBgColor
        self.bidTitleColor = self.containerBgColor
        self.bidTotalPriceColor = self.containerBgColor
        self.bidHoursColor = self.containerBgColor
        self.bidStatusColor = self.containerBgColor
        self.bidPriceColor = self.containerBgColor
        self.bidCancelButtonColor = "red"
        self.offerTitleColor = self.containerBgColor
        self.offerPriceColor = self.containerBgColor
        self.offerHoursColor = self.containerBgColor
        self.offerTotalPriceColor = self.containerBgColor
        self.offerApproveButtonColor = "green"
        self.serviceTitleColor = self.containerBgColor
        self.servicePriceColor = self.containerBgColor
        self.serviceStatusColor = self.containerBgColor
        self.serviceViewLogsButtonColor = self.containerBgColor


myStyle = style()
